sudo: false
language: python
os:
- linux
python:
- '3.5'
- '3.6'
- '3.7'
- '3.9'
addons:
  apt:
    packages:
      - pandoc
install:
- pip install -r requirements.txt
- pip install coveralls
script: nosetests --with-coverage --cover-package=sdfascii
after_success: coveralls
